name: Metrics
on:
  schedule: [{cron: "*/30 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - uses: lowlighter/metrics@master
        with:
          user: ReeceDonovan 
          config_timezone: Europe/London
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
#           committer_token: ${{ secrets.GIT_TOKEN }}
          config_twemoji: yes
          config_gemoji: yes
          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_languages_details: bytes-size, percentage
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14  
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_isocalendar: yes  
          plugin_isocalendar_duration: full-year  
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_identicons: no
#           plugin_music: yes
#           plugin_music_provider: spotify
#           plugin_music_mode: recent
#           plugin_music_limit: 4
#           plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
#           plugin_music_played_at: yes
          plugin_wakatime: yes        
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_user: ReeceDonovan
          plugin_wakatime_days: 7 
          plugin_wakatime_limit: 4
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_notable: yes
          plugin_notable_filter: stars:>500
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: no     
          repositories_forks: yes
